
    version: '3.7'

    services:
      server:
        build: .
        hostname: coordinator
        container_name: coordinator
        networks:
          - default
    
      node0:
        build: .
        hostname: node0
        container_name: node0
        networks:
          - default
      node1:
        build: .
        hostname: node1
        container_name: node1
        networks:
          - default
      node2:
        build: .
        hostname: node2
        container_name: node2
        networks:
          - default
      node3:
        build: .
        hostname: node3
        container_name: node3
        networks:
          - default
      node4:
        build: .
        hostname: node4
        container_name: node4
        networks:
          - default
      node5:
        build: .
        hostname: node5
        container_name: node5
        networks:
          - default

    networks:
      default:
        driver: bridge
    
