# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GHS.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GHS.proto',
  package='ousystems',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tGHS.proto\x12\tousystems\"D\n\x0c\x42\x65ginRequest\x12\x10\n\x08nodename\x18\x01 \x01(\t\x12\x11\n\tneighbors\x18\x02 \x03(\x05\x12\x0f\n\x07weights\x18\x03 \x03(\x05\"2\n\x06MsgAck\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03src\x18\x02 \x01(\t\x12\x0b\n\x03\x64st\x18\x03 \x01(\t\"\x1c\n\tWakeUpMSG\x12\x0f\n\x07nullMSG\x18\x01 \x01(\x05\"5\n\nConnectMSG\x12\x10\n\x08nodename\x18\x01 \x01(\t\x12\x15\n\rfragmentLevel\x18\x02 \x01(\x05\"Y\n\x0bInitiateMSG\x12\x10\n\x08nodename\x18\x01 \x01(\t\x12\x15\n\rfragmentLevel\x18\x02 \x01(\x05\x12\x12\n\nfragmentID\x18\x03 \x01(\x05\x12\r\n\x05state\x18\x04 \x01(\x05\"F\n\x07TestMSG\x12\x10\n\x08nodename\x18\x01 \x01(\t\x12\x15\n\rfragmentLevel\x18\x02 \x01(\x05\x12\x12\n\nfragmentID\x18\x03 \x01(\x05\"1\n\x0f\x41\x63\x63\x65ptRejectMSG\x12\x10\n\x08nodename\x18\x01 \x01(\t\x12\x0c\n\x04\x41orR\x18\x02 \x01(\x05\"-\n\tReportMSG\x12\x10\n\x08nodename\x18\x01 \x01(\t\x12\x0e\n\x06weight\x18\x02 \x01(\x05\"!\n\rChangeCoreMSG\x12\x10\n\x08nodename\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2A\n\x08Gallager\x12\x35\n\x05\x42\x65gin\x12\x17.ousystems.BeginRequest\x1a\x11.ousystems.MsgAck\"\x00\x32\x97\x03\n\tMessaging\x12\x32\n\x06WakeUp\x12\x14.ousystems.WakeUpMSG\x1a\x10.ousystems.Empty\"\x00\x12\x34\n\x07\x43onnect\x12\x15.ousystems.ConnectMSG\x1a\x10.ousystems.Empty\"\x00\x12\x36\n\x08Initiate\x12\x16.ousystems.InitiateMSG\x1a\x10.ousystems.Empty\"\x00\x12\x38\n\x04Test\x12\x12.ousystems.TestMSG\x1a\x1a.ousystems.AcceptRejectMSG\"\x00\x12>\n\x0c\x41\x63\x63\x65ptReject\x12\x1a.ousystems.AcceptRejectMSG\x1a\x10.ousystems.Empty\"\x00\x12\x32\n\x06Report\x12\x14.ousystems.ReportMSG\x1a\x10.ousystems.Empty\"\x00\x12:\n\nChangeCore\x12\x18.ousystems.ChangeCoreMSG\x1a\x10.ousystems.Empty\"\x00\x62\x06proto3')
)




_BEGINREQUEST = _descriptor.Descriptor(
  name='BeginRequest',
  full_name='ousystems.BeginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodename', full_name='ousystems.BeginRequest.nodename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neighbors', full_name='ousystems.BeginRequest.neighbors', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weights', full_name='ousystems.BeginRequest.weights', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=92,
)


_MSGACK = _descriptor.Descriptor(
  name='MsgAck',
  full_name='ousystems.MsgAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ousystems.MsgAck.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src', full_name='ousystems.MsgAck.src', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst', full_name='ousystems.MsgAck.dst', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=144,
)


_WAKEUPMSG = _descriptor.Descriptor(
  name='WakeUpMSG',
  full_name='ousystems.WakeUpMSG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nullMSG', full_name='ousystems.WakeUpMSG.nullMSG', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=174,
)


_CONNECTMSG = _descriptor.Descriptor(
  name='ConnectMSG',
  full_name='ousystems.ConnectMSG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodename', full_name='ousystems.ConnectMSG.nodename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fragmentLevel', full_name='ousystems.ConnectMSG.fragmentLevel', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=229,
)


_INITIATEMSG = _descriptor.Descriptor(
  name='InitiateMSG',
  full_name='ousystems.InitiateMSG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodename', full_name='ousystems.InitiateMSG.nodename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fragmentLevel', full_name='ousystems.InitiateMSG.fragmentLevel', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fragmentID', full_name='ousystems.InitiateMSG.fragmentID', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='ousystems.InitiateMSG.state', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=320,
)


_TESTMSG = _descriptor.Descriptor(
  name='TestMSG',
  full_name='ousystems.TestMSG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodename', full_name='ousystems.TestMSG.nodename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fragmentLevel', full_name='ousystems.TestMSG.fragmentLevel', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fragmentID', full_name='ousystems.TestMSG.fragmentID', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=392,
)


_ACCEPTREJECTMSG = _descriptor.Descriptor(
  name='AcceptRejectMSG',
  full_name='ousystems.AcceptRejectMSG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodename', full_name='ousystems.AcceptRejectMSG.nodename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AorR', full_name='ousystems.AcceptRejectMSG.AorR', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=443,
)


_REPORTMSG = _descriptor.Descriptor(
  name='ReportMSG',
  full_name='ousystems.ReportMSG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodename', full_name='ousystems.ReportMSG.nodename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='ousystems.ReportMSG.weight', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=490,
)


_CHANGECOREMSG = _descriptor.Descriptor(
  name='ChangeCoreMSG',
  full_name='ousystems.ChangeCoreMSG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodename', full_name='ousystems.ChangeCoreMSG.nodename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=525,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='ousystems.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=534,
)

DESCRIPTOR.message_types_by_name['BeginRequest'] = _BEGINREQUEST
DESCRIPTOR.message_types_by_name['MsgAck'] = _MSGACK
DESCRIPTOR.message_types_by_name['WakeUpMSG'] = _WAKEUPMSG
DESCRIPTOR.message_types_by_name['ConnectMSG'] = _CONNECTMSG
DESCRIPTOR.message_types_by_name['InitiateMSG'] = _INITIATEMSG
DESCRIPTOR.message_types_by_name['TestMSG'] = _TESTMSG
DESCRIPTOR.message_types_by_name['AcceptRejectMSG'] = _ACCEPTREJECTMSG
DESCRIPTOR.message_types_by_name['ReportMSG'] = _REPORTMSG
DESCRIPTOR.message_types_by_name['ChangeCoreMSG'] = _CHANGECOREMSG
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BeginRequest = _reflection.GeneratedProtocolMessageType('BeginRequest', (_message.Message,), {
  'DESCRIPTOR' : _BEGINREQUEST,
  '__module__' : 'GHS_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.BeginRequest)
  })
_sym_db.RegisterMessage(BeginRequest)

MsgAck = _reflection.GeneratedProtocolMessageType('MsgAck', (_message.Message,), {
  'DESCRIPTOR' : _MSGACK,
  '__module__' : 'GHS_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.MsgAck)
  })
_sym_db.RegisterMessage(MsgAck)

WakeUpMSG = _reflection.GeneratedProtocolMessageType('WakeUpMSG', (_message.Message,), {
  'DESCRIPTOR' : _WAKEUPMSG,
  '__module__' : 'GHS_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.WakeUpMSG)
  })
_sym_db.RegisterMessage(WakeUpMSG)

ConnectMSG = _reflection.GeneratedProtocolMessageType('ConnectMSG', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTMSG,
  '__module__' : 'GHS_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.ConnectMSG)
  })
_sym_db.RegisterMessage(ConnectMSG)

InitiateMSG = _reflection.GeneratedProtocolMessageType('InitiateMSG', (_message.Message,), {
  'DESCRIPTOR' : _INITIATEMSG,
  '__module__' : 'GHS_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.InitiateMSG)
  })
_sym_db.RegisterMessage(InitiateMSG)

TestMSG = _reflection.GeneratedProtocolMessageType('TestMSG', (_message.Message,), {
  'DESCRIPTOR' : _TESTMSG,
  '__module__' : 'GHS_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.TestMSG)
  })
_sym_db.RegisterMessage(TestMSG)

AcceptRejectMSG = _reflection.GeneratedProtocolMessageType('AcceptRejectMSG', (_message.Message,), {
  'DESCRIPTOR' : _ACCEPTREJECTMSG,
  '__module__' : 'GHS_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.AcceptRejectMSG)
  })
_sym_db.RegisterMessage(AcceptRejectMSG)

ReportMSG = _reflection.GeneratedProtocolMessageType('ReportMSG', (_message.Message,), {
  'DESCRIPTOR' : _REPORTMSG,
  '__module__' : 'GHS_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.ReportMSG)
  })
_sym_db.RegisterMessage(ReportMSG)

ChangeCoreMSG = _reflection.GeneratedProtocolMessageType('ChangeCoreMSG', (_message.Message,), {
  'DESCRIPTOR' : _CHANGECOREMSG,
  '__module__' : 'GHS_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.ChangeCoreMSG)
  })
_sym_db.RegisterMessage(ChangeCoreMSG)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'GHS_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.Empty)
  })
_sym_db.RegisterMessage(Empty)



_GALLAGER = _descriptor.ServiceDescriptor(
  name='Gallager',
  full_name='ousystems.Gallager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=536,
  serialized_end=601,
  methods=[
  _descriptor.MethodDescriptor(
    name='Begin',
    full_name='ousystems.Gallager.Begin',
    index=0,
    containing_service=None,
    input_type=_BEGINREQUEST,
    output_type=_MSGACK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GALLAGER)

DESCRIPTOR.services_by_name['Gallager'] = _GALLAGER


_MESSAGING = _descriptor.ServiceDescriptor(
  name='Messaging',
  full_name='ousystems.Messaging',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=604,
  serialized_end=1011,
  methods=[
  _descriptor.MethodDescriptor(
    name='WakeUp',
    full_name='ousystems.Messaging.WakeUp',
    index=0,
    containing_service=None,
    input_type=_WAKEUPMSG,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='ousystems.Messaging.Connect',
    index=1,
    containing_service=None,
    input_type=_CONNECTMSG,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Initiate',
    full_name='ousystems.Messaging.Initiate',
    index=2,
    containing_service=None,
    input_type=_INITIATEMSG,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Test',
    full_name='ousystems.Messaging.Test',
    index=3,
    containing_service=None,
    input_type=_TESTMSG,
    output_type=_ACCEPTREJECTMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AcceptReject',
    full_name='ousystems.Messaging.AcceptReject',
    index=4,
    containing_service=None,
    input_type=_ACCEPTREJECTMSG,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Report',
    full_name='ousystems.Messaging.Report',
    index=5,
    containing_service=None,
    input_type=_REPORTMSG,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ChangeCore',
    full_name='ousystems.Messaging.ChangeCore',
    index=6,
    containing_service=None,
    input_type=_CHANGECOREMSG,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGING)

DESCRIPTOR.services_by_name['Messaging'] = _MESSAGING

# @@protoc_insertion_point(module_scope)
