# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import GHS_pb2 as GHS__pb2


class GallagerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Begin = channel.unary_unary(
        '/ousystems.Gallager/Begin',
        request_serializer=GHS__pb2.BeginRequest.SerializeToString,
        response_deserializer=GHS__pb2.MsgAck.FromString,
        )


class GallagerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Begin(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GallagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Begin': grpc.unary_unary_rpc_method_handler(
          servicer.Begin,
          request_deserializer=GHS__pb2.BeginRequest.FromString,
          response_serializer=GHS__pb2.MsgAck.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ousystems.Gallager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class MessagingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.WakeUp = channel.unary_unary(
        '/ousystems.Messaging/WakeUp',
        request_serializer=GHS__pb2.WakeUpMSG.SerializeToString,
        response_deserializer=GHS__pb2.Empty.FromString,
        )
    self.Connect = channel.unary_unary(
        '/ousystems.Messaging/Connect',
        request_serializer=GHS__pb2.ConnectMSG.SerializeToString,
        response_deserializer=GHS__pb2.Empty.FromString,
        )
    self.Initiate = channel.unary_unary(
        '/ousystems.Messaging/Initiate',
        request_serializer=GHS__pb2.InitiateMSG.SerializeToString,
        response_deserializer=GHS__pb2.Empty.FromString,
        )
    self.Test = channel.unary_unary(
        '/ousystems.Messaging/Test',
        request_serializer=GHS__pb2.TestMSG.SerializeToString,
        response_deserializer=GHS__pb2.AcceptRejectMSG.FromString,
        )
    self.AcceptReject = channel.unary_unary(
        '/ousystems.Messaging/AcceptReject',
        request_serializer=GHS__pb2.AcceptRejectMSG.SerializeToString,
        response_deserializer=GHS__pb2.Empty.FromString,
        )
    self.Report = channel.unary_unary(
        '/ousystems.Messaging/Report',
        request_serializer=GHS__pb2.ReportMSG.SerializeToString,
        response_deserializer=GHS__pb2.Empty.FromString,
        )
    self.ChangeCore = channel.unary_unary(
        '/ousystems.Messaging/ChangeCore',
        request_serializer=GHS__pb2.ChangeCoreMSG.SerializeToString,
        response_deserializer=GHS__pb2.Empty.FromString,
        )


class MessagingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def WakeUp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Connect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Initiate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Test(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AcceptReject(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Report(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangeCore(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessagingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'WakeUp': grpc.unary_unary_rpc_method_handler(
          servicer.WakeUp,
          request_deserializer=GHS__pb2.WakeUpMSG.FromString,
          response_serializer=GHS__pb2.Empty.SerializeToString,
      ),
      'Connect': grpc.unary_unary_rpc_method_handler(
          servicer.Connect,
          request_deserializer=GHS__pb2.ConnectMSG.FromString,
          response_serializer=GHS__pb2.Empty.SerializeToString,
      ),
      'Initiate': grpc.unary_unary_rpc_method_handler(
          servicer.Initiate,
          request_deserializer=GHS__pb2.InitiateMSG.FromString,
          response_serializer=GHS__pb2.Empty.SerializeToString,
      ),
      'Test': grpc.unary_unary_rpc_method_handler(
          servicer.Test,
          request_deserializer=GHS__pb2.TestMSG.FromString,
          response_serializer=GHS__pb2.AcceptRejectMSG.SerializeToString,
      ),
      'AcceptReject': grpc.unary_unary_rpc_method_handler(
          servicer.AcceptReject,
          request_deserializer=GHS__pb2.AcceptRejectMSG.FromString,
          response_serializer=GHS__pb2.Empty.SerializeToString,
      ),
      'Report': grpc.unary_unary_rpc_method_handler(
          servicer.Report,
          request_deserializer=GHS__pb2.ReportMSG.FromString,
          response_serializer=GHS__pb2.Empty.SerializeToString,
      ),
      'ChangeCore': grpc.unary_unary_rpc_method_handler(
          servicer.ChangeCore,
          request_deserializer=GHS__pb2.ChangeCoreMSG.FromString,
          response_serializer=GHS__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ousystems.Messaging', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
